configure.ac
On many Linux platforms, libm is not linked by default with libc and
must be explicitly added (-lm).  When building these tools on Hera, libm
was not linked and the ceil() function was unavailable.
This patch adds a search for ceil() in configure.ac, which resolves the
build on Hera.
Note that there are many missing libm functions (e.g. my own laptop
fails because of a missing acos() function) so there might be a more
general way of forcing libm to be used.
=> Search libm for ceil()

site-configs/ncrc/env.sh
Closes #7
Bumped versions for PrgEnv-intel, cray-netcdf, cray-hdf5, nccmp
=> Updated gaea env.sh module environment post CLE7 update

.github/workflows/main.yml, Dockerfile, build.sh, t/Makefile.am, t/Test26-reference_fregrid_gcc.sh
Updates the github action to use docker containers to compile and run tests with and without mpi enabled, and will save the log file upon failure.
Also added in a check to skip Test24 since it fails with gcc, and adds Test26 as a workaround for Test24.
=> Improvements for CI and workaround for test

.editorconfig
Adds an .editorconfig file with the initial editor configuration we would like to see in the FMS project. Information at https://editorconfig.org on how to configure specific editors to use the information contained in this file.
fixes #31
=> Added editorconfig file to repository

tools/libfrencutils/mosaic_util.c
Fix poly_area when polygon side crosses a pole fixes issue #45 
- Added the derivation for poly_area formula to the comments .
- The area needs a fix for the case that the polygon side crosses a pole (d(longitude)=+- pi).
In that case the  area formula was missing an additive factor of pi.
- Missing a pi in the formula results a huge discrepancy of the order of the Earth area!
- Similarly, if the polygon has a corner with angle A, then the formula
needs an additive factor of A (in radians). But this latter case is
already handled by fix_lon() and is the reason it creates a twin pole vertex
(with longitudes paired with the preceding and following vertices)
if the original polygon has a vertex at the pole.
- Put the fix also in fix_lon() too. 
- Investigate why putting the fix in poly_area …
=> Fix poly_area when side of grid cell polygon crosses pole

tools/libfrencutils/create_xgrid.c, tools/libfrencutils/create_xgrid.h
- This update addresses and fixes issue #42 
-  Fixes clip_2dx2d for grids surrounding the Poles
- The clip_2dx2d issue #42 seems to arise when the first box passes through
the NorthPole and corners have a longitude greater than 2*pi or when
the SouthPole and corners have a longitude less than 0.
- This heuristic fix shifts ALL the longitudes of the two boxes to be
within -pi and pi and it seems to cure the clipping issues. 
- I can't figure out why this fixes the issue. Need help!
- Shifting all angles (regardless of location of the grid boxes) to be within -pi and pi does not work and ruins the clipper! Only the boxes that cross the poles have to be shifted!
- I added some unit tests to create_xgrid.c to show this.
@ceblanton please assign this for review to @jwdGFDL and @bensonr . …
=> Fix clip 2dx2d cells include poles

tools/make_coupler_mosaic/make_coupler_mosaic.c
- This update closes issue #57  
- This update avoids clipping/calculating ATMxLND exchange grid if
the ATM and LND grids are the same. It simply reuses ATM grid as ATMxLND.
- The above logic is in the GCA algorithm but was missing from the non-GCA
causing unnecessary inaccuracies in exchange grids.
- This update also adds comments and verbosity to the tool that are
useful for debugging
=> Use ATM grid for ATMxLND if ATM and LND grids are the same

.github/workflows/main.yml
Updates the container in which the CI runs to a version Seth had made with a newer version of Ubuntu and nccmp. Fixes the CI crash.
=> Change container to a new ubuntu focal version to fix CI

site-configs/env_functions.sh, site-configs/gfdl-ws/env.sh, site-configs/gfdl/env.sh, site-configs/ncrc/env.sh, site-configs/orion/env.sh
resolves #37 
* Use newer gcc at GFDL and GFDL-ws to handle the new _Generic type handling
* Much improved shell-agnostic environment/module setting site scripts from @underwoo
=> New env.sh site files with updated gcc

t/Makefile.am, t/Test27-multiple_nests.sh, tools/make_hgrid/create_gnomonic_cubic_grid.c
These modifications will allow multiple telescoping nests functionality.
Telescoping nests are defined as nests within nests.
This works for many nest levels.
=> Enable telescoping nests (multiple levels)

.gitignore, t/Test10-remap_land_res.sh, t/Test12-mppnscatter.sh, t/Test21-reference_mppnccombine.sh
@rem1776 I updated a few of the tests using additional `bats` items.  This should do a better job at cleaning up after the tests (even failed tests).  I needed to do this while tracking down a failing tests -- the old method did not clean up after a test failed, causing future tests to fail.
I suggest updating the other tests with similar modifications.
=> Test.updates

.gitlab-ci.yml, site-configs/ncrc/env.sh, site-configs/orion/env.sh, t/Test25-hydrology.sh
* Use the new "eval `env.sh`" method to set the GFDL site environments
* Turn off parallel compilation (make -j)
* Set the SITE_CONFIG variable in ncrc/orion's env.sh script
* Skip the failing hydrology script test if the input dataset is empty
=> Small fixes for GFDL gitlab CI

site-configs/nescc/config.site, site-configs/nescc/env.sh
This adds a working env.sh for use on NESCC systems.
Adds newer `gcc` to `PATH` for Intel to use C11 standards.
Fixes #83
=> Add env.sh for NESCC

site-configs/orion/env.sh
This update adds a newer GCC to PATH to have intel compile with C11 standards.
Fixes #84
=> Update orion env.sh to use newer GCC

site-configs/gfdl-ws/env.sh, site-configs/gfdl/env.sh, site-configs/ncrc/env.sh, site-configs/nescc/env.sh, site-configs/orion/env.sh
#87 Temporary workaround to set the LD_RUN_PATH environment variable until a more native Autotools method can be added.
With this change, users using the site-configs/env.sh file to set their build environment will compile executables that have the rpath properly set (i.e. won't have to set $LD_LIBRARY_PATH in order to run the executables)
=> Set the executable rpath to include needed netcdf libraries

postprocessing/split_ncvars/split_ncvars.pl
resolves #92
In particular, this will help PP/AN CentOS 7 transition
=> Update split_ncvar.pl shebang header to use first perl found in user's PATH

postprocessing/iceberg_comb/iceberg_comb.sh
closes #96
Also update a user message/warning. If an input file doesn't appear
to be a NetCDF file, it's skipped with a message and any other
valid files are combined. The message has been updated to be a
warning instead of an error.
=> iceberg_comb.sh to check for required tool ncdump

site-configs/ncrc/config.site
The compiler flags were modified so that the executables could run on the  DTN AMD Epyc hardware 
as well as the Gaea Intel hardware. It was necessary to change the ncrc config.site file to use the
"-xSSE2" flag in lieu of the "-msse2" flag. It was not necessary to change the flags for the gfdl or the gfdl-ws sites.
One of the goals was also to compile executables whose output was most similar to the fre-bronx/18 output. 
The files compared with the outputs of all the unit tests normally run - a total of 164 files for fre-bronx/18 and 176 from the current baseline.  Compiling with "-xSSE2" produced, by a significant margin,  the least number off non-reproducing files between the baseline and  fre/bronx-18.  With this flag, the ncrc Intel hardware there are 15 (out of 164) non-reproducing …
=> Compiler flags to for release 18.1 - running on AMD and Intel

tools/fregrid/fregrid.c, tools/libfrencutils/mpp_io.c, tools/libfrencutils/mpp_io.h
Fregrid is modified to more closely work as indicated in its usage instructions. According to the
instructions: "When format is not specified, will use the format of input_file." Fregrid now temporarily stores the
netcdf format of the input_file file upon opening it, and if the case where the "format" argument is not specified, it uses
that stored format for the format of the output file. Function reset_in_format was added to mpp_io.
This PR is related to GFDL issue ticket #5019381 ("bronx-18: fregrid fails to remap tiled files with netcdf3/netcdf4 cconfusion") and was tested with the data indicated mentioned in that issue.
NOTE:: This PR replaces PR 106 because the automatic re-formatting created be Visual Code was too great.
=> Use input_file format for the output NetCDF file type if the format argument is not specified

.github/workflows/main.yml, .gitmodules, Makefile.am, README.md, configure.ac, t/Makefile.am, t/Test28-input/hash.md5, t/Test28-om_grid_gen.sh
This pull request adds the ocean_model_grid_generator project ( https://github.com/NOAA-GFDL/ocean_model_grid_generator ) as a submodule to NCTools.  One key goal is to have the
grid generator appear in as much as possible as just another tool of NCTools. To that end : the
grid generator has its own subdirectory under FRE-NCtools/tools; the grid generator (although it is a python script) 
is installed along with the other NCTools scripts; and unit tests were created within NCTools that are in the same 
directory as all the other NCTools unit tests, and are run by the CI.
There are two issues remaining:
1)  One of the four unit tests is commented out as the expected output is not produced. This is currently under investigation.
2) The coordination between the two repositories is still TBD. …
=> ocean_model_grid_generator submodule to NCTools

site-configs/gfdl-ws/config.site, site-configs/gfdl/config.site
Specifying -lm before the object file has the effect of using the standard GNU math library instead of the optimized Intel Math library for C programs. Additionally, add the -xsse2 option to use a stricter set of ISA than the default -msse2, which is also used for the gaea settings.
=> Disable the optimized Intel Math Library for PP/AN and WS compilations

configure.ac, tools/cubic_utils/make_remap_file.c, tools/fregrid/fregrid_util.c, tools/libfrencutils/mpp_io.c, tools/libfrencutils/tool_util.c, tools/libfrencutils/tool_util.h, tools/make_coupler_mosaic/make_coupler_mosaic.c, tools/make_hgrid/make_hgrid.c, tools/make_land_domain/make_land_domain.c, tools/make_quick_mosaic/make_quick_mosaic.c, tools/make_regional_mosaic/make_regional_mosaic.c, tools/make_solo_mosaic/make_solo_mosaic.c, tools/make_topog/make_topog.c, tools/make_vgrid/make_vgrid.c, tools/remap_land/remap_land.c, tools/river_regrid/river_regrid.c, tools/runoff_regrid/runoff_regrid.c
This PR creates print_provenance utility functions to uniformly (accross all NCTols apps using the functions) write as netcdf global attributes provenance and provenance related information.
A sample of the info is 
```
// global attributes:
:grid_version = "0.2" ;
:code_release_version = "19.0.1" ;
:git_hash = "51ed4692c8b238e1e15bbc1d240951d3000e6f35" ;
:creationtime = "Wed Nov 24 13:52:24 2021" ;
:hostname = "edison" ;
:history = "make_hgrid --grid_type gnomonic_ed --nlon 96 --grid_name C48_gridy" ;
```
The new functions are in /tools/libfrencutil/tool_util.c.
configure.ac was modified to place the git_hash info into the generated config.h file.
Numerous apps were modified to use the new functionality.
=> Writing uniform provenance info in netdfs global attributes.

postprocessing/mppnccombine/mppnccombine.c
This PR changes several variables in mppnccombine.c that are indices , or are related to indices, from "int"
to "long long int" - i.e. from 32 bit ints to 64 bit ints. The 32 bit indices could not hold the info when the index
was set to a  number larger that pow(2,32 -1). For example, test files with
``` NLAT * NLON * NTILES = 5400 * 7200 * 64```, that product being greater than pow(2,32-1), 
would evntually  have negative values for variables ```offset```  and ```b``` in loop  calculation such as this one:
```for (l=0; l < lmax; l++)
for (k=0; k < kmax; k++)
for (j=0; j < jmax; j++)
for (i=0; i < imax; i++)
{
offset=(i+ioffset)+
(j+joffset)*imaxfull+
(k+koffset)*imaxjmaxfull+
(l+loffset)*imaxjmaxkmaxfull;
*((unsigned char *)(varbuf[(r % (*bf))][v])+offset)=
*((unsigned char …
```
=> mppnccombine fixes for use with monolithic files

postprocessing/land_utils/is-compressed.c, tools/fregrid/fregrid.c, tools/libfrencutils/constant.h, tools/libfrencutils/create_xgrid.c, tools/libfrencutils/mosaic_util.c, tools/libfrencutils/mosaic_util.h, tools/libfrencutils/mpp.c, tools/libfrencutils/tool_util.c, tools/make_hgrid/create_conformal_cubic_grid.c, tools/make_hgrid/create_gnomonic_cubic_grid.c, tools/make_hgrid/create_grid_from_file.c, tools/make_hgrid/create_lonlat_grid.c, tools/make_topog/make_topog.c, tools/make_topog/topog.c, tools/ncexists/ncexists.c, tools/remap_land/remap_land.c, tools/river_regrid/river_regrid.c, tools/runoff_regrid/runoff_regrid.c
This PR includes several types of changes for successfully compiling with some recent c99 compliant compilers. Teach of these compilers forced one or more of the  forced the changes listed below : gcc 11.1,  Intel 2021.5 and Apple clang version 13.0.0  see (issue https://github.com/NOAA-GFDL/FRE-NCtools/issues/143 ) when used with CFLAG -std=c99. We checked resultant code now compiles with or without the -std=c99 flag with these three compilers, and also with gcc 11.2 and gcc 9.3.
I.1). Constant M_PI is defined in file constant.h after a “#define check” to verify its not already defined. This is because M_PI is not defined in standard C. BTW, the check allows default (non-standard or non c99) compilation. 
I.2)  Since numerous .c files had Pi related constants redefined, these were …
=> Additional changes to build with recent c99 compliant compilers.

configure.ac, m4/gx_c__generic.m4
configure will fail with a note if the C compiler does not support the _Generic selection introduced in C11 - https://en.cppreference.com/w/c/language/generic
Fixes #102
=> build: add _Generic selection test to autoconf

tools/libfrencutils/tool_util.c, tools/libfrencutils/tool_util.h, tools/make_coupler_mosaic/make_coupler_mosaic.c
This PR is for two minor changes to the code to remove new compiler warnings from two recent  code changes. First,  the redefinition of constants R2D and D2R are removed from make_coupler mosaic since they are already defined in the included constant.h file. This change was missed in an earlier merge.
Second, print_provenance_info functions are getting a const qualifier to "char * history" 
argument.  This does not have a functional effect but removed a warning introduced within the 
last year.
=> Minor changes to remove two newer compiler warnings

site-configs/gfdl-ws/env.sh, site-configs/gfdl/env.sh, site-configs/ncrc/env.sh
With the Intel compiler, this was used to include
the netcdf-c and netcdf-fortran library paths during linking.
This does not work for the GCC compiler, so should be removed
in case it has unintended consequences.
#87
=> Remove LD_RUN_PATH env var from GFDL site files

tools/make_hgrid/create_gnomonic_cubic_grid.c
In general for a given stretch factor and target latitude the resulting stretch grid will not have the poles as grid points.
This may cause issues later with other tools such as exchange grid generator manifested as tiling errors and cells with a wrong land mask.
- Work related to issue https://github.com/NOAA-GFDL/FMS/issues/621 in FMS repo (wrong repo for that issue)
- Implement the condition for the stretched grid to have both poles as grid points for a give stretch factor.
- This subroutine lists possible target latitudes for a given stretch factor close to the requested target latitude such that the final grid has both poles as grid points.
- Having a grid that includes both poles potentially avoids later issues with exchange grids. After using the suggested values from this update …
=> Suggest target latitudes so that stretched grid would have both NS poles

tools/make_hgrid/create_gnomonic_cubic_grid.c
Reverts NOAA-GFDL/FRE-NCtools#159
make_hgrid core dumps for certain inputs. See Test04-grid_coupled_nest.sh, second cal to make_hgrid, lines 70ff for an example set of args that can cause a core dump. In function suggest_target_lats, index ls in into array lat[] (line 1361 : 
``` b = -2*(1.0+sin(lat[ln])*sin(lat[ls]))/(sin(lat[ln])+sin(lat[ls])); ```)  may be negative and cause a core dump.
=> Revert "Suggest target latitudes so that stretched grid would have both NS poles"

.gitlab-ci.yml
1. Deploy for master branch or tags
2. Deploy location includes tag name if it exists, branch name otherwise
3. Do not test parallel updates on gaea login nodes as mpirun is not allowed
Related to GFDL site config files for release 2022.01 (#99)
=> Updates for deploying updates for GFDL sites

postprocessing/land_utils/combine-ncc.F90, postprocessing/land_utils/decompress-ncc.F90, postprocessing/land_utils/scatter-ncc.F90
This PR is for the replacement of the use of iargc in NCtools Fortran programs to allow for compiling with certain modern
compilers on ARM. Certain compiler do not (or no longer) support iargc, and even some compilers that currently support it now recommend the use of function command_argument_count() instead . E.g. the GNU Fortran manual states :
" This (iargc) intrinsic routine is provided for backwards compatibility with GNU Fortran 77. In new code, programmers should consider the use of the COMMAND_ARGUMENT_COUNT intrinsic defined by the Fortran 2003 standard."
The issue was discoverer compiling with recent NVidia compilers on Raspberry Pi. The changed was tested with NVidia, GNU, and Intel compilers on linux.
There is a related PR (https://github.com/NOAA-GFDL/FRE-NCtools/pull/183) …
=> iargc replacement in Fortran apps.

tools/libfrencutils/create_xgrid.c, tools/libfrencutils/mosaic_util.c
- Closes issue #180
- The centroid latitude calculation in ploy_ctrlat() needs a small fix similar to the fix in issue #45 for grid cells staddling the South pole but not including it as a vertex.
- Added/corrected comments in poly_area().
- Cleaned up poly_area() of unneeded code.
=> Fix fregrid conserve2 issues for stretched grids

t/test_utils.bash
test_utils.bash contained POSIX unsafe 'expr substr', replaced with shell parameter expansion to grab test directory numbers.
=> Fixing test_utils.bash to be POSIX safe

.vscode/c_cpp_properties.json, t/test_utils.bash, tools/libfrencutils/mpp.c, tools/libfrencutils/mpp_domain.c, tools/make_hgrid/make_hgrid.c, tools/remap_land/remap_land.c, tools/runoff_regrid/runoff_regrid.c
Test07-runoff_regrid.sh runs to completion on MacOS 12.5/Intel upon change to runoff_regrid.c.
=> Fix to runoff_regrid.c

.vscode/c_cpp_properties.json, tools/libfrencutils/mpp.c, tools/libfrencutils/mpp_domain.c, tools/make_hgrid/make_hgrid.c, tools/remap_land/remap_land.c
The files mpp.c and mpp_domain.c shared three variables.  This sharing is removed.  Both files now have `static` global variables.
Cleaned up a few error messages in make_hgrid.c and remap_land.c
Added .vscode mac configuration.
fixes #182
=> Remove shared global vars npes, pe, root_pe

.github/workflows/main.yml, README.md, configure.ac, tools/fregrid/Makefile.am, tools/fregrid/conserve_interp.c, tools/libfrencutils/Makefile.am, tools/libfrencutils/create_xgrid.c, tools/libfrencutils/create_xgrid.h, tools/libfrencutils/mosaic_util.c, tools/libfrencutils/mosaic_util.h
See #204, replaces the code changes made there.
This compiles a separate version of libfrencutils and fregrid with the openacc flags `-acc -O2 -g -tp haswell -gpu=cc70 -Minfo=accel -Mnoinline`and names the executable `fregrid_gpu`.
I tried not bringing in too many unrelated changes from the existing code, but they were mostly unused variables/routines and trailing whitespace removals so it didn't really make sense to not keep those. Not really sure about the conserve_interp.c file though, wasn't going to include it but ended up just adding a debug macro in case we want it for benchmarking/testing.
=> Add in initial openacc code

tools/libfrencutils/create_xgrid.c
In this PR, the `create_xgrid_2dx2d_order2` subroutine has been modified to fix reproducibility issues when running on GPUs.
=> Modified create_xgrid for reproducibility

tools/libfrencutils/create_xgrid.c
The variables `x_out` and `y_out` have been moved to the inner loop of the second kernel.  This change is necessary to get `ncells` reproduciblity when _acc kernels_ is changed to _acc parallel_
=> Change the scope of x_out and y_out 

t/Test01-check_programs_exist.sh, t/Test02-mppnccombine.sh, t/Test03-grid_coupled_model.sh, t/Test04-grid_coupled_nest.sh, t/Test12-mppnscatter.sh, t/Test15-regrid_land.sh, t/Test17-combine-ncc.sh, t/Test18-decompress-ncc.sh, t/Test21-reference_mppnccombine.sh, t/Test22-reference_combine-ncc.sh, t/Test23-reference_decompress-ncc.sh, t/Test24-reference_fregrid.sh, t/Test25-hydrology.sh, t/Test26-reference_fregrid_gcc.sh, t/Test31-fregrid_stretched.sh, t/Test32-fregrid_no_stretched.sh, t/Test33-reference_make_hgrid.sh, t/test_utils.bash
This PR modifies test scripts that checked for answers or function status to use the new run_and_check() function 
found in test_utils.bash. Said function was created in previous PR to echo $output if the status of the
executed command was not 0.
For an example of the output produced in the github CI actions/runs that encounter failures, 
test 32 was forced to fail by giving it a threshold of zero on line 100. This line :
```run_and_check expr ${var_34_0} \< 0.00001```
was changed to this:
```run_and_check expr ${var_34_0} \< 0```
The output produced is:
```
FAIL: Test32-fregrid_no_stretched.sh 1 Test no stretched grid data lats 32.0 34.0 35.4
```
=> Changed to use run_and_check function (found in test_utils.bash) in

tools/libfrencutils/constant.h, tools/libfrencutils/create_xgrid.c, tools/libfrencutils/create_xgrid.h, tools/libfrencutils/mosaic_util.c, tools/libfrencutils/mosaic_util.h, tools/make_coupler_mosaic/make_coupler_mosaic.c, tools/make_hgrid/make_hgrid.c, tools/make_topog/make_topog.c
This PR does the following:
1) adds the  command-line option rotate_poly to make_hgrid, make_coupler_mosaic, and make_topog to use
the polar polygon rotation feature for the purpose of helping the calculation of the area of polar polygons.
2) Creates a wrapper to the original poly_area function so that for polar polygons,
if the global poly_are_flag  is set, the area is calculated by first rotating a copy of the polygon away
from the pole and calculating the area of the rotated polygon instead.
3) Fixes some non-critical typos in constants.h and adds two more constants.
4) Removes some post function definition semicolons. This to remove some compile-time warnings.
This PR is not intended as a final fix to the motivating issue (https://github.com/NOAA-GFDL/FRE-NCtools/issues/44), rather it …
=> Code for changing poly_area by rotating polar polygons away from pole.

configure.ac, tools/libfrencutils/affinity.c
This PR improves  affinity.c by:
1) replacing affinity.c with one copied from FMS/affinity;
2)  modifies configure.ac to check for sched_getaffinity; 
3) modifies the new affinity.c to #include configure.h.
This has been tested with gcc on analysis (an008) with and without the ```--with-mpi``` compilation flag using the canonical compilation method. It has also bee tested on an ubuntu laptop.
I think it would be prudent to build and test on Apple OSX.
FYI, The new affinity.c #includes the generated configure.h file. Somehow FMS is able to compile affinity.c without this change - to my surprise.
=> Improvements to affinity.c

Makefile.am, configure.ac, t/Test-fregrid_scaling.sh.in
adds a scaling test that runs with `make check-scaling` after building with openacc (`--with-openacc`). Does all the conversions listed in `remap_sizes` and creates a new timestamped directory and input for each run. It's separate from the normal test suite.
Right now its not working with this branch cause it needs mikyungs changes merged in. I tested it by setting fregrid_gpu to the built tool from the update code.
=> add gpu scaling test

cpp/libfrencutils/create_xgrid_gpu.C, cpp/search/BBox3D.h
create_grid_2dx2d_order2 for GPUs was updated with missing mask check and missing fix_poly call.
Added or cleaned up miscellaneous comments. GPU code was tested with weight generation
for cubic sphere grids to regular lat-long grids, and cubic sphere grids to cubic sphere grids.
=> update to create_grid_2dx2d_order2 for GPUs with std::copy_if

postprocessing/split_ncvars/split_ncvars.pl
=> Include 4-dimensional (i.e. diurnal) output in default split-vars processing

tools/fregrid/conserve_interp.c, tools/fregrid/globals.h, tools/libfrencutils/Makefile.am, tools/libfrencutils/create_xgrid.c, tools/libfrencutils/create_xgrid_acc.c, tools/libfrencutils/create_xgrid_acc.h, tools/libfrencutils/create_xgrid_util.c, tools/libfrencutils/create_xgrid_util.h
In this PR,
- structure `Minmaxavglists` has been declared to hold all "list" arrays pertaining to the output grid
- function  `get_minmaxavg_lists` has been created.  This function computes values for the "list" arrays in structure Minmaxavglists
- `OpenACC` directives to transfer data to/from the device has been added.
=> Create structures for list arrays and Add OpenACC data transfer directives 

tools/fregrid/conserve_interp.c, tools/fregrid/conserve_interp_util.c, tools/fregrid/conserve_interp_util.h, tools/fregrid/globals.h, tools/libfrencutils/mosaic_util.c, tools/libfrencutils/mosaic_util.h
In this PR, the following functions have been introduced:
1. `get_nxy` which gets the number of grid points in the lat and lon arrays.
2. `get_mask` which mallocs and assigns the mask array
3. `get_start_end` which gets the lat indices of the input grid that overlaps with the output grid
4. `get_interp` which takes the arrays holding the exchange grid information and copies that information over to the interp structure.
=> Create function get_interp

tools/fregrid/conserve_interp.c, tools/fregrid/conserve_interp_util.c, tools/fregrid/conserve_interp_util.h, tools/fregrid/globals.h, tools/libfrencutils/Makefile.am, tools/libfrencutils/create_xgrid.c, tools/libfrencutils/create_xgrid_acc.c, tools/libfrencutils/create_xgrid_acc.h, tools/libfrencutils/create_xgrid_util.c, tools/libfrencutils/create_xgrid_util.h, tools/libfrencutils/mosaic_util.c, tools/libfrencutils/mosaic_util.h
This PR creates a new function called `get_CellStruct`.  This function populates the component arrays of cell_in.
=> create function to populate cell_in

configure.ac, site-configs/gfdl-ws/env.sh, site-configs/gfdl/env.sh
Also, update the GFDL site build configurations to use GFDL SW enviroment version 2023.02. These site files are referenced in the README, but the GFDL Spack deployment of fre-nctools does not use them.
=> Update autoconf package verison to 2023.01.02

postprocessing/timavg/time_average.f90, tools/fregrid/fregrid_util.c
Fixes #273
Fixes #274
I tried this using output from the old diag manager (which includes the average_* variables) and this updated reproduces the master branch.
I tried this using output from the new diag manager (which does not have the average_* variables). This update reproduces the output from the old diag manager.
=> Remove the use of average_* variables and use time_bnds variables instead

configure.ac, tools/libfrencutils/create_xgrid.h, tools/make_topog/make_topog.c, tools/river_regrid/river_regrid.c
=> Adjust the size of MAXXGRID for serial/non-mpi builds

tools/fregrid/fregrid_util.c
After https://github.com/NOAA-GFDL/FRE-NCtools/pull/278, fregrid does not write the average_* variables, but the time_avg_info variable attribute still exists.
This causes issues with [split_ncvars.pl](http://split_ncvars.pl/) fails when trying to splitting the regridded output. It is seeing the "average_T1" in the time_avg_info attribute but fails when trying to include it in the split-out output.
With this PR, the time_avg_info attribute is not longer written.
=> Do not write time_avg_info variable attribute in fregrid

tools/make_topog/CHANGELOG, tools/make_topog/make_topog.c, tools/make_topog/topog.c, tools/make_topog/topog.h
We introduced option "on_grid" which skips the regridding function. Using make_topog , we experienced changes in the topography even if the topography is on the target grid and "--dont_adjust_topo" is active. The reason seems to be that the topography is always passed through the regridding.
=> Additional option "on_grid" for make_topog

postprocessing/split_ncvars/split_ncvars.pl
The semicolon at the end of the each ncdump line can be used for the regex.
resolves #297
=> Change split_ncvars.pl regex to work for dimensionless variables

postprocessing/split_ncvars/split_ncvars.pl
resolves #297
Embarrassingly, #298 was broken and only worked with dimensionless variables but we need it work for both types.
It's hand tested for both types of variables, this time.
=> Change split_ncvars.pl regex to work for both dimensionless and with-dimensions

site-configs/ncrc6/config.site, site-configs/ncrc6/env.sh
=> Add ncrc6 env.sh to load C6 modules

tools/fregrid/bilinear_interp.c
The portion of the code in setup_bilinear where the entire input grid is scanned to find the nearest  input cells to the output cell location seem to contain two bugs.  
The incrementation of the for loop index is changed from `j` to `jc`
Great circle distance is fixed and is now computed between vectors v0 and `v1`, not v0 and `v2`.
This section of the code is executed only if the first round of finding "nearest" input cells to an output cell fails and may have gone unnoticed?
=> Fix index error and incorrect vector input  in setup_bilinear_interp

.github/workflows/main.yml, configure.ac, m4/gx_openacc_flags.m4, tools/fregrid_acc/Makefile.am, tools/libfrencutils_acc/Makefile.am, tools/mppncscatter/mppncscatter.c
adds an m4 for checking valid openacc flags with compilers that support it (currently only nvc and gcc).
Also adds a header that was needed for mppncscatter to compile with intel due to the sync updates (forgot function order matters for C, gcc doesn't seem to care though) .
=> add m4 check for openacc flags and fix for intel

.github/workflows/main.yml
updates the ci image to a rocky 9 image with spack installed dependencies. The dockerfile is [here.](https://github.com/NOAA-GFDL/HPC-ME/pull/8)
=> Update CI image

tools/libfrencutils_acc/create_xgrid_acc.c, tools/libfrencutils_acc/create_xgrid_utils_acc.c, tools/libfrencutils_acc/globals_acc.h
In this PR, 
`lon_vertices` and `lat_vertices` members in the `Grid_cell_struct_config` struct have been changed from double pointers to single pointers and are now malloc-ed to be 1d arrays.  This change has been made after testing showed that computation with 1d arrays is faster than with 2d arrays on GPUs.
=> fregrid_acc - convert 2d lon/lat_vertices arrays to 1d arrays 

.github/workflows/main.yml
Github just deprecated the version of the action that uploads the build log, so this just bumps its up to the most recent version.
=> update deprecated `upload-artifact` action version

postprocessing/split_ncvars/split_ncvars.pl
=> Let split_ncvars split large Netcdf-4 files

tools/libfrencutils/mosaic_util.c, tools/libfrencutils/mosaic_util.h, tools/make_coupler_mosaic/make_coupler_mosaic.c, tools/make_quick_mosaic/make_quick_mosaic.c
=> remove deprecated `reproduce_siena` option 

.github/workflows/main.yml
changes the ci image to a new one that has the netcdf operators (nco) package installed. On my fork this image was able to configure and build correctly with #317 merged in.
=> update CI image with nco package

postprocessing/mppnccombine/mppnccombine.c
If no netCDF format is specified (no -64 or -n4 options) for the  output file then use the netCDF format of the first input file; use netCDF3 64-bit offset format or netCDF4 classic format.
=> Update mppnccombine.c to V2.2.8

configure.ac
This PR fixes the missed argument changes from `acc` to `gpu` in `configure.ac`.
Fixes #332 
**How Has This Been Tested?**
Fregrid_gpu compiles with ./configure --enable-gpu=yes
**Checklist:**
=> Fix gpu compile error from PR #328

tools/make_land_domain/make_land_domain.c
In `make_land_domain.c`, allocate `nx*ny` integers per face in the `land_ntile` array, rather than `nx*nx`.
This doesn't make a difference when `nx == ny`, but should be the correct behavior in the general case.
**How Has This Been Tested?**
Compiles with icx 2023.2.0
**Checklist:**
=> make_land_domain: Allocate `land_ntile` array to correct size

configure.ac, src/split_ncvars/split_ncvars.pl.in
This is a patch fix for 2024.05.01 to the split_ncvars.pl command.  This adds `bin` to the patch for list_ncvars.sh.  This needs to be merged in to future releases.  We should also tag this branch with 2024.05.02.
=> Fix path to list_ncvars in split_ncvars

.github/workflows/tag.yaml, .github/workflows/version.yml
adds a workflow that grabs the version number from the `configure.ac` and creates a new tag for releases. It will be triggered whenever `configure.ac` is modified but will not overwrite previously created tags. The grep command will match both `xxx.xx.xx` and `xxx.xx` style version numbers. End result basically ensures each new version number committed to main will have a corresponding tag.
Since my other PR is triggered by a tag (#357) and creates the release draft, once these both go in we'd have a (almost) fully automated release process. A PR containing a change to the version number would be merged in to main, and then we would just have to wait for the actions to run and manually release the created draft.
This kind of thing has potential for script injections, so I …
=> add workflow for automatic tag creation
